spring:
  application:
    name: studymate
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/studymate}
    username: ${SPRING_DATASOURCE_USERNAME:studymate}
    password: ${SPRING_DATASOURCE_PASSWORD:studymate}

server:
  port: ${SERVER_PORT:8080}

studymate:
  storage:
    local-root: ${STUDYMATE_STORAGE_LOCAL_ROOT:./data/uploads}
