import { useState } from "react";

const availableDocuments = ["Bai giang 01.pdf", "Chu de microservice.docx"];
const initialMessages = [{ role: "assistant", text: "Chon tai lieu san sang va dat cau hoi. Cau tra loi se hien thi nguon de ban kiem chung.", citations: [] }];

export default function StudySessionPage() {
  const [selected, setSelected] = useState([availableDocuments[0]]);
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState(initialMessages);
  function toggleDocument(name) { setSelected(selected.includes(name) ? selected.filter((item) => item !== name) : [...selected, name]); }
  function send(event) { event.preventDefault(); if (!question.trim()) return; const asked = question.trim(); const next = [...messages, { role: "user", text: asked }]; if (!selected.length) next.push({ role: "assistant", text: "Hay chon it nhat mot tai lieu san sang truoc khi dat cau hoi.", citations: [] }); else if (asked.toLowerCase().includes("ngoai tai lieu")) next.push({ role: "assistant", text: "Khong tim thay thong tin phu hop trong tai lieu da chon. Hay thu cau hoi cu the hon hoac chon them tai lieu.", citations: [] }); else next.push({ role: "assistant", text: "Dependency injection la cach cung cap phu thuoc tu ben ngoai cho mot doi tuong, thay vi de doi tuong tu tao phu thuoc. Cach nay giup de kiem thu va thay the cac thanh phan hon.", citations: [{ document: selected[0], location: "Trang 12 · Dependency injection" }] }); setMessages(next); setQuestion(""); }
  return <section className="study-layout" aria-labelledby="session-title"><aside className="context-panel"><p className="eyebrow">Phien hoc</p><h1 id="session-title">Hoi dap co nguon</h1><p>Chi cac tai lieu san sang moi duoc dung lam ngu canh.</p><fieldset><legend>Chon tai lieu</legend>{availableDocuments.map((document) => <label className="document-choice" key={document}><input checked={selected.includes(document)} onChange={() => toggleDocument(document)} type="checkbox" />{document}</label>)}</fieldset></aside><div className="chat-panel"><div className="chat-history">{messages.map((message, index) => <article className={`message message-${message.role}`} key={index}><p>{message.role === "user" ? "Ban" : "StudyMate"}</p><div>{message.text}</div>{message.citations?.map((citation) => <div className="citation" key={citation.location}>Nguon: {citation.document} · {citation.location}</div>)}</article>)}</div><form className="chat-form" onSubmit={send}><label htmlFor="question">Dat cau hoi tu tai lieu da chon</label><textarea id="question" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Vi du: Dependency injection la gi?" rows="3" /><button className="primary-button" type="submit">Gui cau hoi</button></form></div></section>;
}
