ALTER TABLE chat_messages
    ADD COLUMN grounding_status VARCHAR(30);

CREATE TABLE study_session_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES study_sessions(id) ON DELETE CASCADE,
    document_id BIGINT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    UNIQUE (session_id, document_id)
);

CREATE INDEX idx_study_session_documents_session_id
    ON study_session_documents(session_id);

CREATE INDEX idx_study_session_documents_document_id
    ON study_session_documents(document_id);
